{% set name = "enterprise_extensions" %}
{% set version = "2.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2e3bca9830ebc24d4c30a971b2c15ac74e4a7bbc060c4cd63f868e1c6d6a3139

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.16.3
    - scipy >=1.2.0
    - ephem >=3.7.6.0
    - healpy >=1.14.0
    - scikit-sparse >=0.4.5
    - pint-pulsar >=0.8.2
    - libstempo >=2.4.0
    - enterprise-pulsar >=3.1.0
    - emcee
    - ptmcmcsampler

test:
  requires:
    - python {{ python_min }}
  imports:
    - enterprise_extensions
    - enterprise_extensions.chromatic
    - enterprise_extensions.frequentist

about:
  home: https://github.com/nanograv/enterprise_extensions
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A set of extension codes, utilities, and scripts for the enterprise PTA analysis framework.
  description: |
    enterprise_extensions is a package that contains various utilities and
    model recipes for the pulsar timing array data analysis suite, enterprise
    (the enterprise-pulsar conda package). Various frequentist statistics and
    Bayesian models are included, as well as support for a hypermodel framework
    and MCMC sampling support.
  # doc_url: https://enterprise_extensions.readthedocs.io/
  dev_url: https://github.com/nanograv/enterprise_extensions

extra:
  recipe-maintainers:
    - Hazboun6
    - AaronDJohnson
    - paulthebaker
