{% set name = "enterprise_extensions" %}
{% set version = "3.0.2" %}
{% set python_min = "3.9" %}
{% set python_max = "3.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5d127f92bce690bc391a9435caf3646e70527378f5ad9e7d8868c60d4ef27ec9

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy >=1.16.3
    - scipy >=1.2.0
    - ephem >=3.7.6.0
    - healpy >=1.14.0
    - scikit-sparse >=0.4.5
    - enterprise-pulsar >=3.4.4
    - pyarrow >=16.1.0
    - scikit-learn >=0.24
    - matplotlib >=3.1.0
    - six
    - emcee
    - ptmcmcsampler

test:
  requires:
    - python {{ python_min }}
  imports:
    - enterprise_extensions
    - enterprise_extensions.chromatic
    - enterprise_extensions.frequentist

about:
  home: https://github.com/nanograv/enterprise_extensions
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A set of extension codes, utilities, and scripts for the enterprise PTA analysis framework.
  description: |
    enterprise_extensions is a package that contains various utilities and
    model recipes for the pulsar timing array data analysis suite, enterprise
    (the enterprise-pulsar conda package). Various frequentist statistics and
    Bayesian models are included, as well as support for a hypermodel framework
    and MCMC sampling support.
  # doc_url: https://enterprise_extensions.readthedocs.io/
  dev_url: https://github.com/nanograv/enterprise_extensions

extra:
  recipe-maintainers:
    - Hazboun6
    - AaronDJohnson
    - paulthebaker
